services:
  zoo1:
    image: confluentinc/cp-zookeeper:7.7.7
    container_name: zoo1
    hostname: zoo1
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_SERVERS: zoo1:2888:3888
    networks:
      - spring
  kafka1:
    image: confluentinc/cp-kafka:7.7.7
    container_name: kafka1
    hostname: kafka1
    depends_on:
      - zoo1
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_REPLICA_FETCHERS: 1
      KAFKA_NUM_RECOVERY_THREADS_PER_DATA_DIR: 1
      KAFKA_MESSAGE_MAX_BYTES: 10485767
      KAFKA_NUM_NETWORK_THREADS: 150
      KAFKA_IO_THREADS: 80
      KAFKA_BACKGROUND_THREADS: 80
      KAFKA_SOCKET_SEND_BUFFER_BYTES: 10485760
      KAFKA_SOCKET_RECEIVE_BUFFER_BYTES: 10485760
      KAFKA_SOCKET_REQUEST_MAX_BYTES: 41943040
      KAFKA_FETCH_MAX_BYTES: 41943040
      KAFKA_REPLICA_FETCH_MAX_BYTES: 10485760
      KAFKA_REPLICA_FETCH_RESPONSE_MAX_BYTES: 41943040
      KAFKA_LOG_SEGMENT_BYTES: 1073741824
      KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: 300000
    networks:
      - spring

networks:
  spring:
    driver: bridge